-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc powder
profiles['powder'] = S{
    'prize powder',
}

-- //sellnpc ore
profiles['ore'] = S{
    'iron ore',
    'copper ore',
    'tin ore',
}

-- //sellnpc junk
profiles['junk'] = S{
    'chestnut',
    'san d\'Or. carrot',
    '4leaf mandra bud',
    'eggplant',
    'bluetail',
    'red terrapin',
    'kazham pineapl.',
    'bastore bream',
    'pipira',
    'giant catfish',
    'crescent fish',
    'bhefhel marlin',
    'shall shell',
    'elshimo newt',
    'yayinbaligi',
    'winterflower',
    'black prawn',
    'senroh sardine',
    'brass flowerpot',
    'vegetable seeds',
    'darksteel ore',
    'elm log',
    'maple log',
    'mahogany log',
    'bone chip',
    'bat fang',
    'scorpion claw',
    'pine nuts',
    '2leaf mandra bud',
    'dark bass',
    'black eel',
    'crayfish',
    'copper frog',
    'ca cuong',
    'walnut',
    'moat carp creel',
    'felicifruit',
    'herb seeds',
    'ogre pumpkin',
    'moko grass',
    'crawler cocoon',
    'insect wing',
    'pugil scales',
    'sheep tooth',
    'red rose',
    'igneous rock',
    'skull locust',
    'king locust',
    'snapping mole',
    'snow geode',
    'thunder geode',
    'aqua geode',
    'ifritite',
    'shivite',
    'ramuite',
    'loc. elutriator',
    'cobalt jellyfish',
    'moorish idol',
    'contortopus',
    'adoulinian kelp',
    'paralyze',
    'barsleep',
    'auspice',
    'regen ii',
    'mage\'s ballad',
    'foe lullaby',
    'faerie shield',
    'marine hat',
    'bonze\'s circlet',
    'bird whistle',
    'rusty bucket',
    'seashell',
    'revival root',
    'eastern gem',
    'flame geode',
    'soil geode',
    'porxie pork',
    'porxie wing',
    'tin ore',
    'spider web',
    'iron sand',
    'twitherym wing',
    'acheron shield',
    'pebble',
    'meteorite',
    'iron ore',
    'shadow geode',
    'fenrite',
    'zebra eel',
    'woozyshroom',
    'pamamas',
    'three-eyed fish',
    'cone calamary',
    'grain seeds',
    'ash log',
    'flax flower',
    'umbril ooze',
    'acorn',
    'little worm',
    'mythril ore',
    'beetle jaw',
    'persikos',
    'grimmonite',
    'rolanberry',
    'gold carp',
    'yagudo cherry',
    'black ghost',
    'date',
    'fish bones',
    'marguerite',
    'lesser chigoe',
    'chapuli wing',
    'moat carp',
    'roast mutton',
    'gigant squid',
    'gavial fish',
    'brass loach',
    'mackerel',
    'arrowwood log',
    'dogwood log',
    'carnation',
    'fresh marjoram',
    'urunday log',
    'land crab meat',
    'crab shell',
    'bat wing',
    'fiend blood',
    'light bead',
    'wootz ore',
    'amb. pseudopod',
    'garudite',
    'leviatite',
    'carbite',
    'wyrdstrand',
    'flint caviar',
    'crawler egg',
    'napa',
    'saruta cotton',
    'tomato juice',
    'aurora bass',
    'ebony log',
    'mercury',
    'silver leaf',
    'asphodel',
    'breeze geode',
    'grove cuttings'
}

return profiles
